spring:
  application:
    name: order-api
  datasource:
    url: jdbc:mysql://mysql:3306/ticketing
    username: ticket
    password: ticketpw
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    jdbc:
      time_zone: Asia/Seoul

  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: order-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    service:
      name: order-api
  otlp:
    tracing:
      endpoint: http://jaeger:4318/v1/traces

server:
  port: 8082
