spring:
  application:
    name: reservation-api
  jackson:
    serialization:
      write-dates-as-timestamps: false
  kafka:
    admin:
      properties:
        auto.create.topics.enable: true
    bootstrap-servers: kafka:29092
    consumer:
      group-id: reservation-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  data:
    redis:
      host: redis
      port: 6379
  datasource:
    url: jdbc:mysql://mysql:3306/ticketing
    username: ticket
    password: ticketpw
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none   # ✅ Hibernate가 테이블 생성/수정하지 않도록
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    jdbc:
      time_zone: Asia/Seoul

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,configprops
  endpoint:
    health:
      show-details: always
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    service:
      name: reservation-api
  otlp:
    tracing:
      endpoint: http://jaeger:4318/v1/traces

server:
  port: 8081
