name: Deploy Ticketing Project (BE only)

on:
  push:
    branches: [ "main" ]   # main 브랜치 push 시 자동 배포

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. JDK 17 세팅
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Reservation 모듈 빌드 & 푸시
      - name: Build & Push Reservation Image
        run: |
          cd ticketing
          ./gradlew jib \
            -Djib.to.image=ghcr.io/tpdus751/reservation:latest \
            -Djib.to.auth.username=tpdus751 \
            -Djib.to.auth.password=${{ secrets.GHCR_TOKEN }} \
            --no-configuration-cache

      # 4. Order 모듈 빌드 & 푸시
      - name: Build & Push Order Image
        run: |
          cd ticketing
          ./gradlew jib \
            -Djib.to.image=ghcr.io/tpdus751/order:latest \
            -Djib.to.auth.username=tpdus751 \
            -Djib.to.auth.password=${{ secrets.GHCR_TOKEN }} \
            --no-configuration-cache

      # 5. Payment 모듈 빌드 & 푸시
      - name: Build & Push Payment Image
        run: |
          cd ticketing
          ./gradlew jib \
            -Djib.to.image=ghcr.io/tpdus751/payment:latest \
            -Djib.to.auth.username=tpdus751 \
            -Djib.to.auth.password=${{ secrets.GHCR_TOKEN }} \
            --no-configuration-cache

      # 6. Catalog 모듈 빌드 & 푸시
      - name: Build & Push Catalog Image
        run: |
          cd ticketing
          ./gradlew jib \
            -Djib.to.image=ghcr.io/tpdus751/catalog:latest \
            -Djib.to.auth.username=tpdus751 \
            -Djib.to.auth.password=${{ secrets.GHCR_TOKEN }} \
            --no-configuration-cache

      # 7. EC2 접속 & 배포
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}      # EC2 퍼블릭 IP
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}    # pem 파일 내용
          script: |
            cd /srv/ticketing/ticketing-project
            git fetch origin
            git checkout main
            git pull origin main   
            cd ticketing/infra
            sudo docker compose pull
            sudo docker compose -f docker-compose.prod.yml up -d
